2024-01-11 11:42:33.886 +04:00 [INF] CategoryService.GetAllAsync - Categories Get successfully
2024-01-11 11:44:31.065 +04:00 [INF] CategoryService.GetAsync - Category Get successfully.  ID: 55
2024-01-11 11:44:44.719 +04:00 [ERR] CategoryService.GetAsync - Category not found. ID: 100
2024-01-11 11:46:21.876 +04:00 [INF] CategoryService.GetAsync - Category Get successfully.  ID: 55
2024-01-11 11:46:31.904 +04:00 [ERR] CategoryService.GetAsync - Category not found. ID: 100
2024-01-11 11:47:05.974 +04:00 [INF] CategoryService.GetAsync - Category Get successfully.  ID: 55
2024-01-11 11:47:15.638 +04:00 [ERR] CategoryService.GetAsync - Category not found. ID: 1000
2024-01-11 11:47:24.641 +04:00 [ERR] CategoryService.GetAsync - Category not found. ID: 0
2024-01-11 11:47:33.146 +04:00 [ERR] CategoryService.GetAsync - Category not found. ID: 0
2024-01-11 11:47:51.024 +04:00 [ERR] CategoryService.GetAsync - Category not found. ID: 0
2024-01-11 11:48:40.419 +04:00 [INF] AccountController.Login({"Email":"rufatnasibli@gmail.com","Password":"Rufat123"}
2024-01-11 11:50:15.573 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 11:50:33.388 +04:00 [ERR] LocationService.GetAsync - InvalidOperationException:Errors: Complaint not found or does not belong to the authenticated user.
2024-01-11 11:50:53.436 +04:00 [INF] ComplaintService.AddAsync - Complaint Added Succesfully. Data: {"ComplaintText":"string"}
2024-01-11 11:51:07.108 +04:00 [INF] ComplaintService.GetAsync - Complaint Getted Succesfully. Id: 12
2024-01-11 11:51:20.666 +04:00 [ERR] LocationService.GetAsync - InvalidOperationException:Errors: Complaint not found
2024-01-11 12:18:37.523 +04:00 [INF] CategoryService.GetAsync - Category Get successfully.  ID: 55
2024-01-11 12:19:07.680 +04:00 [INF] LocationService.GetAllAsync - Locations Get successfully
2024-01-11 12:20:30.711 +04:00 [INF] LocationService.GetAllAsync - Locations Get successfully
2024-01-11 12:20:30.767 +04:00 [ERR] LocationController.GetAllLocation()
2024-01-11 12:30:32.428 +04:00 [INF] LocationService.GetAllAsync - Locations Get successfully
2024-01-11 12:30:32.490 +04:00 [ERR] LocationController.GetAllLocation()
2024-01-11 12:31:19.475 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: No service for type 'DAL.Filter.ActionFilter.StandardizeResponseFilter' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.ServiceFilterAttribute.CreateInstance(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.ProvideFilter(FilterProviderContext context, FilterItem filterItem)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.OnProvidersExecuting(FilterProviderContext context)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.CreateUncachedFiltersCore(IFilterProvider[] filterProviders, ActionContext actionContext, List`1 filterItems)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.GetAllFilters(IFilterProvider[] filterProviders, ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Routing.ControllerRequestDelegateFactory.<>c__DisplayClass12_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 12:32:15.652 +04:00 [INF] LocationService.GetAllAsync - Locations Get successfully
2024-01-11 12:33:35.544 +04:00 [INF] LocationService.GetAllAsync - Locations Get successfully
2024-01-11 12:35:17.788 +04:00 [INF] LocationService.GetAsync - Location Get successfully.  ID: 27
2024-01-11 12:50:00.621 +04:00 [INF] LocationService.GetAllAsync - Locations Get successfully
2024-01-11 12:50:39.554 +04:00 [FTL] Application startup exception
System.InvalidOperationException: A suitable constructor for type 'BLL.CustomException.GlobalExceptionMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2024-01-11 12:51:01.284 +04:00 [FTL] Application startup exception
System.InvalidOperationException: A suitable constructor for type 'BLL.CustomException.GlobalExceptionMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2024-01-11 12:51:51.727 +04:00 [FTL] Application startup exception
System.InvalidOperationException: A suitable constructor for type 'BLL.CustomException.GlobalExceptionMiddleware' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2024-01-11 12:52:55.681 +04:00 [INF] LocationService.GetAllAsync - Locations Get successfully
2024-01-11 12:53:52.081 +04:00 [ERR] LocationService.GetProductsWithLocationId - Location not found 
2024-01-11 12:54:23.524 +04:00 [INF] AccountController.Login({"Email":"string","Password":"string"}
2024-01-11 12:54:23.545 +04:00 [ERR] AccountController.Login({"Email":"string","Password":"string"}
2024-01-11 12:54:39.702 +04:00 [INF] AccountController.Login({"Email":"rufetnesibli2004@gmail.com","Password":"asdasd"}
2024-01-11 12:54:39.840 +04:00 [ERR] AccountController.Login({"Email":"rufetnesibli2004@gmail.com","Password":"asdasd"}
2024-01-11 12:54:51.687 +04:00 [INF] AccountController.Login({"Email":"rufetnesibli2004@gmail.com","Password":"Rufat123"}
2024-01-11 12:54:54.638 +04:00 [ERR] AccountController.Login({"Email":"rufetnesibli2004@gmail.com","Password":"Rufat123"}
2024-01-11 12:56:01.909 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 12:56:51.883 +04:00 [INF] ComplaintService.GetAsync - Complaint Getted Succesfully. Id: 12
2024-01-11 12:56:59.948 +04:00 [ERR] LocationService.GetAsync - InvalidOperationException:Errors: Complaint not found
2024-01-11 12:57:31.198 +04:00 [INF] ProductController.GetALlProducts()
2024-01-11 12:59:10.778 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 13:00:01.330 +04:00 [INF] CategoryService.GetAllAsync - Categories Get successfully
2024-01-11 13:47:18.054 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 13:48:03.442 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 13:49:34.392 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 13:51:12.078 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 13:53:17.503 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: This is a test exception.
   at API.Controllers.CategoryController.ThrowException() in C:\Users\user\Desktop\Tapaz\TAPAZ\API\Controllers\CategoryController.cs:line 122
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 13:55:01.905 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 14:11:57.084 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 14:12:58.269 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 14:14:50.478 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 14:19:37.900 +04:00 [INF] CategoryService.GetAllAsync - Categories Get successfully
2024-01-11 14:22:26.937 +04:00 [ERR] An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at BLL.CustomException.GlobalExceptionMiddleware.HandleExceptionAsync(HttpContext context, Exception ex)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 32
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-01-11 14:26:51.157 +04:00 [ERR] An error occurred while processing the request.
System.InvalidOperationException: This is a test exception.
   at API.Controllers.CategoryController.ThrowException() in C:\Users\user\Desktop\Tapaz\TAPAZ\API\Controllers\CategoryController.cs:line 122
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 28
2024-01-11 14:27:59.897 +04:00 [ERR] An error occurred while processing the request.
System.InvalidOperationException: This is a test exception.
   at API.Controllers.CategoryController.ThrowException() in C:\Users\user\Desktop\Tapaz\TAPAZ\API\Controllers\CategoryController.cs:line 122
   at lambda_method2(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at BLL.CustomException.GlobalExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\user\Desktop\Tapaz\TAPAZ\BLL\CustomException\GlobalExceptionMiddleware.cs:line 28
2024-01-11 15:01:30.700 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 15:01:52.802 +04:00 [INF] ProductController.DeleteProduct({"Id":11})
2024-01-11 20:14:18.081 +04:00 [INF] AccountController.Register({"Email":"tural@gmail.com","Password":"Rufat123","Fullname":"Tural Quliyev","Address":"Gunesli","Photo":{"ContentType":"image/jpeg","ContentDisposition":"form-data; name=\u0022Photo\u0022; filename=\u0022Image 4.jpg\u0022","Headers":{"Content-Disposition":["form-data; name=\u0022Photo\u0022; filename=\u0022Image 4.jpg\u0022"],"Content-Type":["image/jpeg"]},"Length":2027960,"Name":"Photo","FileName":"Image 4.jpg"},"PhoneNumber":"\u002B994 70 845 24 18"}
2024-01-11 20:14:46.800 +04:00 [INF] AccountController.Login({"Email":"tural@gmail.com","Password":"Rufat123"}
2024-01-11 20:17:01.585 +04:00 [INF] AccountController.Login({"Email":"tural@gmail.com","Password":"Rufat123"}
2024-01-11 20:17:15.205 +04:00 [INF] ProductController.CreateProduct({"Name":"Divan","Description":"Ideal vezyetdedir ","IsNew":false,"IsDelivered":true,"Price":360,"Photos":[{"ContentType":"image/jpeg","ContentDisposition":"form-data; name=\u0022Photos\u0022; filename=\u0022Image 3.jpg\u0022","Headers":{"Content-Disposition":["form-data; name=\u0022Photos\u0022; filename=\u0022Image 3.jpg\u0022"],"Content-Type":["image/jpeg"]},"Length":1172254,"Name":"Photos","FileName":"Image 3.jpg"}],"LocationId":27,"CategoryId":55})
2024-01-11 20:30:40.730 +04:00 [INF] AccountController.Login({"Email":"tural@gmail.com","Password":"Rufat123"}
2024-01-11 20:31:07.083 +04:00 [ERR] An exception occurred while iterating over the results of a query for context type 'DAL.Data.MyDbContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2024-01-11 20:32:27.186 +04:00 [ERR] FavouriteAddDto.AddAsync - InvalidOperationException:Errors: 
2024-01-11 20:32:49.923 +04:00 [INF] AccountController.Login({"Email":"tural@gmail.com","Password":"Rufat123"}
2024-01-11 20:33:27.197 +04:00 [INF] FavouriteService.AddAsync - Favourite Added Succesfully. Data: DTO.FavouriteAddDto
2024-01-11 20:34:02.597 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 20:34:31.626 +04:00 [ERR] An exception occurred while iterating over the results of a query for context type 'DAL.Data.MyDbContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2024-01-11 20:36:36.937 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 20:37:10.148 +04:00 [ERR] An exception occurred while iterating over the results of a query for context type 'DAL.Data.MyDbContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2024-01-11 20:37:19.330 +04:00 [ERR] FavouriteAddDto.AddAsync - InvalidOperationException:Errors: 
2024-01-11 20:37:50.598 +04:00 [INF] FavouriteService.AddAsync - Favourite Added Succesfully. Data: DTO.FavouriteAddDto
2024-01-11 20:38:49.382 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 20:39:31.292 +04:00 [INF] AccountController.Login({"Email":"inci@gmail.com","Password":"Rufat123"}
2024-01-11 20:40:34.983 +04:00 [INF] ProductController.CreateProduct({"Name":"Samsung S 5","Description":"Qa","IsNew":true,"IsDelivered":true,"Price":3400,"Photos":[{"ContentType":"image/jpeg","ContentDisposition":"form-data; name=\u0022Photos\u0022; filename=\u0022Image 4.jpg\u0022","Headers":{"Content-Disposition":["form-data; name=\u0022Photos\u0022; filename=\u0022Image 4.jpg\u0022"],"Content-Type":["image/jpeg"]},"Length":2027960,"Name":"Photos","FileName":"Image 4.jpg"}],"LocationId":28,"CategoryId":50})
2024-01-11 20:40:43.446 +04:00 [INF] AccountController.Login({"Email":"tural@gmail.com","Password":"Rufat123"}
2024-01-11 20:41:24.454 +04:00 [INF] FavouriteService.AddAsync - Favourite Added Succesfully. Data: DTO.FavouriteAddDto
2024-01-11 20:41:39.917 +04:00 [ERR] FavouriteAddDto.AddAsync - InvalidOperationException:Errors: Favorite already exists.
2024-01-11 20:47:20.180 +04:00 [INF] AccountController.Login({"Email":"tural@gmail.com","Password":"Rufat123"}
2024-01-11 20:47:36.662 +04:00 [INF] FavouriteService.GetAllAsync - Favourite Getted All Succesfully.
